Para calcular las liquidaciones por escenario, utilizamos datos de la LFT, artículo 50 y generamos una función reactiva en **R**.

```{r}
library(ggplot2)
library(eem)
library(reshape2)

indemnizacion_mx <- function(tipo, 
                             ingreso = "2013-01-01", 
                             salida = "2014-01-02", 
                             sueldo_mes, 
                             dias_vacacion = 6,
                             porcent_prima = 0.25, 
                             dias_aguinaldo = 15,
                             salario_min){
  
  salida <- as.Date(salida)
  ingreso <- as.Date(ingreso)
  # calcular variables
  v.sueldo_diario <- sueldo_mes/30
  v.prima_diario <- dias_vacacion*v.sueldo_diario*porcent_prima/365
  v.aguinaldo_diario <- dias_aguinaldo*v.sueldo_diario/365
  
  v.sal_diario_int <- v.sueldo_diario + v.prima_diario + v.aguinaldo_diario
  v.sal_mes_int <- v.sal_diario_int*30

  if(tipo == 1){  
    # indeterminado  
    constitucional <- 3*v.sal_mes_int
    
    if((salida-ingreso)>365)
      {
      a <- floor(as.numeric(salida-ingreso)/365)
      if(a==0){a<-1}else{}
      }else{ a <- 0}
    dias_servicio <- (20*a)*v.sal_diario_int
    proporcional <- 20*v.sal_diario_int/360*300
    
    # para prima antiguedad
    v.prima_salariomax <- salario_min*2*(12*a)
    v.prima_salariomin <- salario_min*(12*a)
    v.prima_doble <- if(v.sal_diario_int > (salario_min*2)){TRUE}else{FALSE}
    v.prima_calculo <- v.sal_diario_int*12*a
    
    antiguedad <- if(v.prima_doble){v.prima_salariomax}else{
      if(v.prima_calculo<v.prima_salariomin){v.prima_salariomin}else{
        v.prima_calculo
      }
    }
      indemnizacion <- data.frame("Concepto" = c("Constitucional", 
                                                 "Servicio",
                                                 "Prima Antiguedad"),
                                  "Valor" = c(constitucional, 
                                              dias_servicio + proporcional,
                                              antiguedad)
                                  )
  }else{
    if(tipo == 2){
      #determinado
      if((salida-ingreso)<365){
        meses_lab <- floor((salida-ingreso)/30)
        contrato <- meses_lab*sueldo_mes*0.5
        constitucional <- 0
      }else{
        contrato <- v.sal_mes_int*6
        constitucional <- 3*v.sal_mes_int
      }
      indemnizacion <- data.fram("Concepto" = c("Contrato", 
                                                  "Constitucional"),
                                   "Valor" = c(contrato, 
                                               constitucional))
    }else{}
    
  }
  return(indemnizacion)
}

```



```{r}
# con mismo tiempo, variando sueldos.
pagos <- NULL
porcentajes <- NULL
for(i in 6000:80000){
ind <- indemnizacion_mx(tipo = 1,
                       ingreso = "2014-12-27", 
                       salida = "2016-01-30",
                       sueldo_mes = i,
                       dias_vacacion = 10, 
                       porcent_prima = 0.25, 
                       dias_aguinaldo = 15, 
                       salario_min = 66)
pagos[i-5999] <- sum(ind$Valor)
porcentajes[i-5999] <- (sum(ind$Valor)/i-1)*100
}

ggplot(data.frame("i" = 6000:80000,
                  "pagos" = porcentajes), 
       aes(x = i, 
           y = pagos))+
  geom_point()+
  theme_eem_white()+
  labs(title = "Indemnización esperada como porcentaje del sueldo", 
       x = "Sueldo base mensual (no integrado)",
       y = "Porcentaje")

```


```{r}
# con mismo sueldo, variando tiempo.
pagos2 <- NULL
porcentajes2 <- NULL
for(i in 1:10000){
ind <- indemnizacion_mx(tipo = 1,
                       ingreso = "2014-12-27", salida = as.Date("2016-01-30")+i,
                       sueldo_mes = 10000,
                       dias_vacacion = 10, 
                       porcent_prima = 0.25, dias_aguinaldo = 15, salario_min = 66)
pagos2[i] <- sum(ind$Valor)/1000
porcentajes2[i] <- sum(ind$Valor)/10000*100
}

ggplot(data.frame("i" = 1:10000,
                  "pagos" = pagos2), 
       aes(x = i, 
           y = pagos))+
  geom_point()+
  theme_eem_white()+
  labs(title = "Indemnización esperada nominal", 
       x = "Días en trabajo", 
       y = "Miles de Pesos")


ggplot(data.frame("i" = 1:10000,
                  "porcentajes" = porcentajes2), 
       aes(x = i, 
           y = porcentajes))+
  geom_point()+
  theme_eem_white()+
  labs(title = "Indemnización esperada como porcentaje de sueldo", 
       x = "Días en trabajo", 
       y = "Porcentaje")
```



```{r}
# con varianza proporcional
inflacion <- 0.04
tasa_natural <- 0.025
pagos3 <- NULL
porcentajes3 <- NULL
for(i in 1:10000){
sueldo <- 6000*((1+inflacion)^((365+i)/365))*((1+tasa_natural)^((365+i)/365))

ind <- indemnizacion_mx(tipo = 1,
                       ingreso = "2014-12-27", salida = as.Date("2016-01-30")+i,
                       sueldo_mes = sueldo,
                       dias_vacacion = 10 + (2*floor(-1*as.numeric(as.Date("2014-12-27")-as.Date("2016-01-30")+i)/365)), 
                       porcent_prima = 0.25, 
                       dias_aguinaldo = 15, 
                       salario_min = 66)

pagos3[i] <- sum(ind$Valor)/1000
porcentajes3[i] <- sum(ind$Valor)/sueldo*100
}

ggplot(data.frame("i" = 1:10000,
                  "pagos" = pagos3), 
       aes(x = i, 
           y = pagos))+
  geom_point()+
  theme_eem_white()+
  labs(title = "Indemnización esperada nominal",
       x = "Días en trabajo", 
       y = "Miles de pesos")


ggplot(data.frame("i" = 1:10000,
                  "porcentajes" = porcentajes3), 
       aes(x = i, 
           y = porcentajes))+
  geom_point()+
  theme_eem_white()+
  labs(title = "Indemnización esperada como porcentaje de sueldo",
       x = "Días en trabajo", 
       y = "Porcentaje")
```

# Estadísticas INEGI

## Personal ocupado
```{r}

library(inegiR)
token <- "61c36253-47f6-c616-034e-7bf43b1aaba4"
url_1 <- "http://www3.inegi.org.mx//sistemas/api/indicadores/v1//Indicador/5000000002/00/es/false/json/"
url_2 <- "http://www3.inegi.org.mx//sistemas/api/indicadores/v1//Indicador/5000000001/00/es/false/json/"
personal <- serie_inegi(url_1, token)
unidades <- serie_inegi(url_2, token)

```

# Mercado (Empresas)
```{r}

load("empresas_tidy.RData")

# grafica 
ggplot(order_axis(subset(empresas_tidy,
                         GEOGRAFIA == "00 Nal" &
                             variable == "EMPRESAS" &
                             SECTOR == "TODOS" &
                             SIZE != "TODOS"),
                  DESC_RUBRO, value),
       aes(y = value/1000,
           x = DESC_RUBRO_o)) +
    geom_bar(stat = "identity", fill = eem_colors[1]) +
    theme_eem_white() +
    labs(title = "Empresas por número de empleados",
         x = "Número empleados",
         y = "Miles de Empresas")

# ultimo decil
set_nacional <- subset(empresas_tidy, 
                       GEOGRAFIA == "00 Nal" & 
                         variable == "EMPRESAS" & 
                         SECTOR == "TODOS" & SIZE != "TODOS")

set_nacional$TAM <- c(1,4,8,13,18,25,40,75,175,350,750,2000)
vector_empleados <- set_nacional$TAM * set_nacional$value
suma_empleados <- sum(set_nacional$TAM * set_nacional$value)
set_nacional$P <- vector_empleados/suma_empleados

trabajadores_totales <- subset(empresas_tidy, 
                               GEOGRAFIA == "00 Nal"  & 
                                 variable == "TOTAL_TRAB" &
                                 SECTOR == "TODOS" & SIZE != "TODOS")

ggplot(order_axis(trabajadores_totales,
                  DESC_RUBRO, value),
       aes(y = value/1000,
           x = DESC_RUBRO_o)) +
    geom_bar(stat = "identity", fill = eem_colors[1]) +
    theme_eem_white() +
    labs(title = "Trabajadores por empresa de trabajo",
         x = "Número empleados (tamaño)",
         y = "Miles de Trabajadores")

# share trabajadores

share_top2 <- sum(subset(trabajadores_totales, 
                         SIZE == "Mas de mil" | 
                           SIZE == "500 a mil")$value)/sum(trabajadores_totales$value)
```


# Función de seguro simple

```{r}
seguro_despido <- function(sueldo,
                           suma_liquidacion, 
                           porcentaje_prima,
                           meses_esperados,
                           ganancias_empresa_antes, 
                           tasa_impositiva){
  fondo_individual <- meses_esperados*porcentaje_prima*sueldo
  pago <- fondo_individual-suma_liquidacion
  empresa <- (ganancias_empresa_antes*tasa_impositiva)-((ganancias_empresa_antes - (porcentaje_prima*sueldo))*tasa_impositiva)
  df <- data.frame(fondo_individual, 
                   pago,
                   empresa)
  return(df)
                           }
```

# Corridas por albercas de riesgo

```{r}

# variando costo de mensualidad
individuos <- NULL
empresa <- NULL

ganancias_apv <- NULL
ganancias_empresa <- NULL

for(c in 1:10){
p_prima <- c/100  
  # 500 empleados, media 12 mil pesos, desv. 2
sueldos <- rnorm(500, mean = 12, sd = 2)
  # 30 meses en promedio de antiguedad
meses <- rnorm(500, mean = 30, sd = 4)

    for(i in 1:500){
      
      individuos[i]<-seguro_despido(
        sueldo = sueldos[i],
        suma_liquidacion = sueldos[i]*2,
        porcentaje_prima = p_prima,
        meses_esperados = meses[i],
        ganancias_empresa_antes = 100,
        tasa_impositiva = 0.3
        )$pago
      
      empresa[i]<-seguro_despido(
        sueldo = sueldos[i],
        suma_liquidacion = sueldos[i]*2,
        porcentaje_prima = 0.07,
        meses_esperados = meses[i],
        ganancias_empresa_antes = 100,
        tasa_impositiva = 0.3
        )$empresa
    }

ganancias_apv[c] <- sum(individuos)
ganancias_empresa[c] <- sum(empresa)
}

df_difprimas <- melt(data.frame("apv" = ganancias_apv/1000, 
                           "empresa" = ganancias_empresa/1000,
                           "prima" = 1:10/100), 
                     id.vars = "prima")

ggplot(df_difprimas, 
       aes(x = prima, 
           y = value, 
           group = variable)) +
  geom_line()+
  labs(title = "Prima y ganancia esperada \n empresa con 500 empleados", 
       x = "Prima", y = "Ganancias (miles de pesos)") +
  theme_eem_white()

```

```{r}

# variando tamaño de empresa
individuos <- NULL
empresa <- NULL

ganancias_apv <- NULL
ganancias_empresa <- NULL
n_empleados <- NULL

for(c in 1:10){
p_prima <- 8/100  
  # 500 empleados, media 12 mil pesos, desv. 2
sueldos <- rnorm(c*100, mean = 12, sd = 2)
  # 30 meses en promedio de antiguedad
meses <- rnorm(c*100, mean = 30, sd = 4)

    for(i in 1:(c*100)){
      
      individuos[i]<-seguro_despido(
        sueldo = sueldos[i],
        suma_liquidacion = sueldos[i]*2,
        porcentaje_prima = p_prima,
        meses_esperados = meses[i],
        ganancias_empresa_antes = 100,
        tasa_impositiva = 0.3
        )$pago
      
      empresa[i]<-seguro_despido(
        sueldo = sueldos[i],
        suma_liquidacion = sueldos[i]*2,
        porcentaje_prima = 0.07,
        meses_esperados = meses[i],
        ganancias_empresa_antes = 100,
        tasa_impositiva = 0.3
        )$empresa
    }

ganancias_apv[c] <- sum(individuos)
ganancias_empresa[c] <- sum(empresa)
n_empleados[c]<-c*100
}

df_difprimas <- melt(data.frame("apv" = ganancias_apv/1000, 
                           "empresa" = ganancias_empresa/1000,
                           "empleados" = n_empleados), 
                     id.vars = "empleados")

ggplot(df_difprimas, 
       aes(x = empleados, 
           y = value, 
           group = variable)) +
  geom_line()+
  labs(title = "Prima y ganancia esperada \n empresa con n empleados", 
       x = "Empleados", y = "Ganancias (miles de pesos)") +
  theme_eem_white()

```


```{r}

# variando meses que duran en empleo los trabajadores
individuos <- NULL
empresa <- NULL

ganancias_apv <- NULL
ganancias_empresa <- NULL
meses_empleados <- NULL

for(c in 1:8){
p_prima <- 8/100  
  # 500 empleados, media 12 mil pesos, desv. 2
sueldos <- rnorm(500, mean = 12, sd = 2)
  # meses en promedio de antiguedad
meses <- rnorm(500, mean = (6*c), sd = 5)

    for(i in 1:8){
      
      individuos[i]<-seguro_despido(
        sueldo = sueldos[i],
        suma_liquidacion = sueldos[i]*2,
        porcentaje_prima = p_prima,
        meses_esperados = meses[i],
        ganancias_empresa_antes = 100,
        tasa_impositiva = 0.3
        )$pago
      
      empresa[i]<-seguro_despido(
        sueldo = sueldos[i],
        suma_liquidacion = sueldos[i]*2,
        porcentaje_prima = 0.07,
        meses_esperados = meses[i],
        ganancias_empresa_antes = 100,
        tasa_impositiva = 0.3
        )$empresa
    }

ganancias_apv[c] <- sum(individuos)
ganancias_empresa[c] <- sum(empresa)
meses_empleados[c]<-(6*c)
}

df_difprimas <- melt(data.frame("apv" = ganancias_apv/1000, 
                           "empresa" = ganancias_empresa/1000,
                           "meses" = meses_empleados), 
                     id.vars = "meses")

ggplot(df_difprimas, 
       aes(x = meses, 
           y = value, 
           group = variable)) +
  geom_line()+
  labs(title = "Prima y ganancia esperada \n empresa con 500 empleados", 
       x = "Meses promedio en trabajo", y = "Ganancias (miles de pesos)") +
  theme_eem_white()
```



